### ISSUE TITLE
How are the icons being set?

### ISSUE THREAD

**Issue by ricburton** [kolpanic/SwiftPrefs#3]
Thank you so much for sharing this. Super helpful.

Out of curiosity, how are these icons being set? I couldn’t find any image files or references to images in the framework.

<img width="148" alt="screen shot 2015-10-27 at 13 47 02" src="https://cloud.githubusercontent.com/assets/438160/10750519/4d590076-7cb1-11e5-8067-fde04939a191.png">

Cheers!

**Comment by kolpanic** [comment]
The Preferences View Controller scene is a tab view controller, with a Toolbar style.
![screen shot 2015-10-27 at 7 52 52 am](https://cloud.githubusercontent.com/assets/117055/10757265/1bfa3e7c-7c80-11e5-88b5-34654f9182d8.png)

Each of trhe tab view controller's tabs has its image set to one of the system-provided images.
![screen shot 2015-10-27 at 7 53 00 am](https://cloud.githubusercontent.com/assets/117055/10757268/22f7cabe-7c80-11e5-880a-92668f799925.png)
